---
# handlers file for zabbix-server

- name: restart iptables
  service:
    name=iptables
    state=restarted

- name: start zabbix-server
  service:
    name=zabbix-server
    state=started
    enabled=yes

- name: restart httpd
  service:
    name=httpd
    state=restarted
